-- 202610090003_konsol_pengaturan.sql
-- Konsol Pengaturan Admin (sisi database): pengaturan berversi (draf -> uji -> aktif -> rollback),
-- rahasia terenkripsi aplikasi (AES-256-GCM; kunci induk di env, BUKAN di DB), dan riwayat perubahan.
-- Pertama dipakai untuk rantai LLM (kunci 'llm.rantai_chat'); tabel bersifat generik.
--
-- Akses: SEMUA tabel & fungsi di sini HANYA service_role (RLS aktif TANPA policy; REVOKE dari
-- anon/authenticated). Tulis hanya lewat route admin (requireAdmin) -> RPC di bawah.
-- Tidak bergantung pada migrasi RBAC yang belum diterapkan (hanya memakai petugas & audit_log).
--
-- Terapkan atomik:  node scripts/apply-migration.mjs supabase/migrations/202610090003_konsol_pengaturan.sql --atomic --yes
-- Rollback: docs/rollback-rbac-konsol-202610090003.sql. Kontrak frontend: docs/RBAC_KONSOL_KONTRAK.md

-- ============================================================
-- 1. Tabel
-- ============================================================
CREATE TABLE IF NOT EXISTS public.rahasia_pengaturan (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nama        text NOT NULL CHECK (char_length(nama) BETWEEN 1 AND 80),
  ciphertext  text NOT NULL,
  iv          text NOT NULL,
  tag         text NOT NULL,
  key_id      smallint NOT NULL DEFAULT 1,
  last4       text NOT NULL DEFAULT '' CHECK (char_length(last4) <= 4),
  diubah_oleh uuid REFERENCES public.petugas(id) ON DELETE SET NULL,
  diubah_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.pengaturan_sistem (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  kategori      text NOT NULL CHECK (char_length(kategori) BETWEEN 1 AND 40),
  kunci         text NOT NULL CHECK (kunci ~ '^[a-z0-9_.]{3,64}$'),
  nilai         jsonb NOT NULL,
  versi         integer NOT NULL CHECK (versi > 0),
  status        text NOT NULL CHECK (status IN ('draf', 'aktif', 'arsip')),
  alasan        text CHECK (alasan IS NULL OR char_length(alasan) <= 500),
  hasil_uji     jsonb NOT NULL DEFAULT '{}'::jsonb,
  diuji_at      timestamptz,
  diubah_oleh   uuid REFERENCES public.petugas(id) ON DELETE SET NULL,
  dibuat_at     timestamptz NOT NULL DEFAULT now(),
  diaktifkan_at timestamptz,
  CONSTRAINT pengaturan_sistem_kunci_versi_key UNIQUE (kunci, versi)
);
-- Paling banyak satu versi aktif dan satu draf per kunci.
CREATE UNIQUE INDEX IF NOT EXISTS uq_pengaturan_aktif ON public.pengaturan_sistem (kunci) WHERE status = 'aktif';
CREATE UNIQUE INDEX IF NOT EXISTS uq_pengaturan_draf  ON public.pengaturan_sistem (kunci) WHERE status = 'draf';

CREATE TABLE IF NOT EXISTS public.pengaturan_riwayat (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kunci      text NOT NULL,
  aksi       text NOT NULL CHECK (aksi IN ('simpan_draf', 'aktifkan', 'rollback')),
  versi_lama integer,
  versi_baru integer NOT NULL,
  alasan     text,
  oleh       uuid REFERENCES public.petugas(id) ON DELETE SET NULL,
  at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_pengaturan_riwayat_kunci ON public.pengaturan_riwayat (kunci, at DESC);

ALTER TABLE public.rahasia_pengaturan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pengaturan_sistem  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pengaturan_riwayat ENABLE ROW LEVEL SECURITY;
-- Sengaja TANPA policy: anon/authenticated tidak punya jalur sama sekali.
REVOKE ALL ON TABLE public.rahasia_pengaturan FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.pengaturan_sistem  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.pengaturan_riwayat FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.rahasia_pengaturan TO service_role;
GRANT ALL ON TABLE public.pengaturan_sistem  TO service_role;
GRANT ALL ON TABLE public.pengaturan_riwayat TO service_role;

-- ============================================================
-- 2. RPC (service_role saja). Kode galat di awal pesan dipetakan route ke status HTTP.
-- ============================================================
-- 2a. Simpan draf. Hasil uji dipertahankan HANYA untuk entri yang isinya tidak berubah.
CREATE OR REPLACE FUNCTION public.simpan_draf_pengaturan(
  p_kunci text, p_kategori text, p_nilai jsonb, p_oleh uuid, p_alasan text
) RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_prev public.pengaturan_sistem%ROWTYPE;
  v_draf_id uuid;
  v_versi integer;
  v_uji jsonb := '{}'::jsonb;
BEGIN
  IF p_kunci = 'llm.rantai_chat' AND pg_catalog.jsonb_typeof(p_nilai) <> 'array' THEN
    RAISE EXCEPTION 'NILAI_TIDAK_VALID: rantai LLM harus berupa daftar' USING ERRCODE = '22023';
  END IF;
  PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext('pengaturan:' || p_kunci));

  SELECT s.id INTO v_draf_id FROM public.pengaturan_sistem AS s WHERE s.kunci = p_kunci AND s.status = 'draf' FOR UPDATE;
  SELECT * INTO v_prev FROM public.pengaturan_sistem AS s
   WHERE s.kunci = p_kunci AND s.status IN ('draf', 'aktif') ORDER BY (s.status = 'draf') DESC LIMIT 1;

  IF v_prev.id IS NOT NULL
     AND pg_catalog.jsonb_typeof(p_nilai) = 'array' AND pg_catalog.jsonb_typeof(v_prev.nilai) = 'array' THEN
    SELECT COALESCE(pg_catalog.jsonb_object_agg(u.key, u.value), '{}'::jsonb) INTO v_uji
    FROM pg_catalog.jsonb_each(v_prev.hasil_uji) AS u
    WHERE EXISTS (
      SELECT 1
      FROM pg_catalog.jsonb_array_elements(p_nilai) AS n(e)
      JOIN pg_catalog.jsonb_array_elements(v_prev.nilai) AS o(e) ON n.e = o.e
      WHERE n.e ->> 'id' = u.key
    );
  END IF;

  IF v_draf_id IS NOT NULL THEN
    UPDATE public.pengaturan_sistem
       SET nilai = p_nilai, hasil_uji = v_uji, diuji_at = NULL, alasan = p_alasan, diubah_oleh = p_oleh
     WHERE id = v_draf_id
    RETURNING versi INTO v_versi;
  ELSE
    SELECT COALESCE(MAX(s.versi), 0) + 1 INTO v_versi FROM public.pengaturan_sistem AS s WHERE s.kunci = p_kunci;
    INSERT INTO public.pengaturan_sistem (kategori, kunci, nilai, versi, status, alasan, hasil_uji, diubah_oleh)
    VALUES (p_kategori, p_kunci, p_nilai, v_versi, 'draf', p_alasan, v_uji, p_oleh);
  END IF;

  INSERT INTO public.pengaturan_riwayat (kunci, aksi, versi_lama, versi_baru, alasan, oleh)
  VALUES (p_kunci, 'simpan_draf', NULL, v_versi, p_alasan, p_oleh);
  INSERT INTO public.audit_log (actor_id, actor_role, aksi, entitas, entitas_id, detail)
  VALUES (p_oleh, 'admin', 'pengaturan_simpan_draf', 'pengaturan', p_kunci,
          pg_catalog.jsonb_build_object('versi', v_versi));
  RETURN v_versi;
END $$;

-- 2b. Aktifkan draf. Rantai LLM: setiap entri AKTIF wajib lulus uji, kecuali p_tanpa_uji + alasan >= 5 karakter.
CREATE OR REPLACE FUNCTION public.aktifkan_pengaturan(
  p_kunci text, p_versi integer, p_oleh uuid, p_alasan text, p_tanpa_uji boolean DEFAULT false
) RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_row public.pengaturan_sistem%ROWTYPE;
  v_lama integer;
BEGIN
  PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext('pengaturan:' || p_kunci));
  SELECT * INTO v_row FROM public.pengaturan_sistem AS s WHERE s.kunci = p_kunci AND s.versi = p_versi FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'TIDAK_ADA: versi pengaturan tidak ditemukan' USING ERRCODE = 'P0002';
  END IF;
  IF v_row.status <> 'draf' THEN
    RAISE EXCEPTION 'BUKAN_DRAF: hanya draf yang dapat diaktifkan (gunakan rollback untuk versi lama)' USING ERRCODE = '22023';
  END IF;
  IF p_tanpa_uji AND pg_catalog.char_length(pg_catalog.btrim(COALESCE(p_alasan, ''))) < 5 THEN
    RAISE EXCEPTION 'ALASAN_WAJIB: aktifkan tanpa uji membutuhkan alasan' USING ERRCODE = '22023';
  END IF;
  IF NOT p_tanpa_uji AND p_kunci = 'llm.rantai_chat' THEN
    IF pg_catalog.jsonb_typeof(v_row.nilai) <> 'array' OR NOT EXISTS (
         SELECT 1 FROM pg_catalog.jsonb_array_elements(v_row.nilai) AS e WHERE (e ->> 'aktif') = 'true') THEN
      RAISE EXCEPTION 'TIDAK_ADA_PENYEDIA_AKTIF: minimal satu penyedia harus aktif' USING ERRCODE = '22023';
    END IF;
    IF EXISTS (
         SELECT 1 FROM pg_catalog.jsonb_array_elements(v_row.nilai) AS e
          WHERE (e ->> 'aktif') = 'true'
            AND COALESCE(v_row.hasil_uji -> (e ->> 'id') ->> 'ok', 'false') <> 'true') THEN
      RAISE EXCEPTION 'BELUM_DIUJI: setiap penyedia aktif harus lulus uji sebelum diaktifkan' USING ERRCODE = '22023';
    END IF;
  END IF;

  UPDATE public.pengaturan_sistem SET status = 'arsip'
   WHERE kunci = p_kunci AND status = 'aktif' RETURNING versi INTO v_lama;
  UPDATE public.pengaturan_sistem
     SET status = 'aktif', diaktifkan_at = pg_catalog.now(), diubah_oleh = p_oleh,
         alasan = COALESCE(NULLIF(pg_catalog.btrim(p_alasan), ''), alasan)
   WHERE id = v_row.id;

  INSERT INTO public.pengaturan_riwayat (kunci, aksi, versi_lama, versi_baru, alasan, oleh)
  VALUES (p_kunci, 'aktifkan', v_lama, p_versi, p_alasan, p_oleh);
  INSERT INTO public.audit_log (actor_id, actor_role, aksi, entitas, entitas_id, detail)
  VALUES (p_oleh, 'admin', 'pengaturan_aktifkan', 'pengaturan', p_kunci,
          pg_catalog.jsonb_build_object('versi_lama', v_lama, 'versi_baru', p_versi, 'tanpa_uji', p_tanpa_uji));
  RETURN p_versi;
END $$;

-- 2c. Rollback: salin versi lama menjadi versi BARU yang aktif (sejarah tidak pernah ditimpa).
CREATE OR REPLACE FUNCTION public.rollback_pengaturan(
  p_kunci text, p_versi_sumber integer, p_oleh uuid, p_alasan text
) RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_src public.pengaturan_sistem%ROWTYPE;
  v_lama integer;
  v_baru integer;
BEGIN
  IF pg_catalog.char_length(pg_catalog.btrim(COALESCE(p_alasan, ''))) < 5 THEN
    RAISE EXCEPTION 'ALASAN_WAJIB: rollback membutuhkan alasan' USING ERRCODE = '22023';
  END IF;
  PERFORM pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtext('pengaturan:' || p_kunci));
  SELECT * INTO v_src FROM public.pengaturan_sistem AS s WHERE s.kunci = p_kunci AND s.versi = p_versi_sumber;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'TIDAK_ADA: versi pengaturan tidak ditemukan' USING ERRCODE = 'P0002';
  END IF;
  IF v_src.status <> 'arsip' THEN
    RAISE EXCEPTION 'BUKAN_ARSIP: rollback hanya untuk versi arsip' USING ERRCODE = '22023';
  END IF;

  UPDATE public.pengaturan_sistem SET status = 'arsip'
   WHERE kunci = p_kunci AND status = 'aktif' RETURNING versi INTO v_lama;
  SELECT MAX(s.versi) + 1 INTO v_baru FROM public.pengaturan_sistem AS s WHERE s.kunci = p_kunci;
  INSERT INTO public.pengaturan_sistem
    (kategori, kunci, nilai, versi, status, alasan, hasil_uji, diuji_at, diubah_oleh, diaktifkan_at)
  VALUES
    (v_src.kategori, p_kunci, v_src.nilai, v_baru, 'aktif',
     'Rollback ke v' || p_versi_sumber || ': ' || pg_catalog.btrim(p_alasan),
     v_src.hasil_uji, v_src.diuji_at, p_oleh, pg_catalog.now());

  INSERT INTO public.pengaturan_riwayat (kunci, aksi, versi_lama, versi_baru, alasan, oleh)
  VALUES (p_kunci, 'rollback', v_lama, v_baru, 'Rollback ke v' || p_versi_sumber || ': ' || pg_catalog.btrim(p_alasan), p_oleh);
  INSERT INTO public.audit_log (actor_id, actor_role, aksi, entitas, entitas_id, detail)
  VALUES (p_oleh, 'admin', 'pengaturan_rollback', 'pengaturan', p_kunci,
          pg_catalog.jsonb_build_object('versi_lama', v_lama, 'versi_baru', v_baru, 'versi_sumber', p_versi_sumber));
  RETURN v_baru;
END $$;

REVOKE ALL ON FUNCTION public.simpan_draf_pengaturan(text, text, jsonb, uuid, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.aktifkan_pengaturan(text, integer, uuid, text, boolean) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.rollback_pengaturan(text, integer, uuid, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.simpan_draf_pengaturan(text, text, jsonb, uuid, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.aktifkan_pengaturan(text, integer, uuid, text, boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.rollback_pengaturan(text, integer, uuid, text) TO service_role;

-- ============================================================
-- 3. Dokumen Peraturan untuk bot: match_dokumen_layanan
--    Seperti match_dokumen, tetapi dokumen umum (layanan_id NULL) IKUT dicari selain dokumen layanan
--    terpilih, dan parameter vektor TIDAK mengunci dimensi (indeks bisa 768 atau 3072; dimensi yang
--    tidak cocok menghasilkan galat yang ditangkap bot -> turun ke FAQ/FTS). match_dokumen lama tidak diubah.
-- ============================================================
CREATE OR REPLACE FUNCTION public.match_dokumen_layanan(
  p_embedding       extensions.vector,
  p_match_threshold double precision DEFAULT 0.7,
  p_match_count     integer DEFAULT 3,
  p_layanan_id      uuid DEFAULT NULL
)
RETURNS TABLE (
  id uuid, dokumen_id uuid, nomor_pasal text, teks text, judul text, jenis text, sumber_url text, similarity double precision
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public, extensions
AS $$
  SELECT dp.id, dp.dokumen_id, dp.nomor_pasal, dp.teks, dok.judul, dok.jenis, dok.sumber_url,
         1.0 - (dp.embedding <=> p_embedding) AS similarity
  FROM public.dokumen_potongan AS dp
  JOIN public.dokumen_peraturan AS dok ON dok.id = dp.dokumen_id
  WHERE dok.status = 'berlaku'
    AND dp.embedding IS NOT NULL
    AND (dok.layanan_id IS NULL OR p_layanan_id IS NULL OR dok.layanan_id = p_layanan_id)
    AND 1.0 - (dp.embedding <=> p_embedding) >= p_match_threshold
  ORDER BY dp.embedding <=> p_embedding
  LIMIT LEAST(GREATEST(p_match_count, 1), 10)
$$;
REVOKE ALL ON FUNCTION public.match_dokumen_layanan(extensions.vector, double precision, integer, uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.match_dokumen_layanan(extensions.vector, double precision, integer, uuid) TO service_role;
