-- 202608310003_absensi_foto_fo.sql
-- SUPERSEDED — foto absensi + bucket dikerjakan di migrasi Tahap 1.
--
-- Berkas ini sengaja dikosongkan (no-op). Isi lamanya (DROP FUNCTION lalu CREATE OR REPLACE untuk
-- fungsi pencatatan absensi tanpa cek akses, plus kolom foto dan bucket storage) akan menimpa cek
-- peran di 202610080001_rbac_tahap0_keamanan.sql bila diterapkan sesudahnya.
-- Berkas ini belum pernah diterapkan di produksi (diverifikasi 2026-10-08: kolom foto absensi dan
-- bucket absensi-foto tidak ada) dan bukan baseline. Nama berkas dipertahankan agar daftar
-- migrasi (migration-test-utils.ts) tidak patah.
-- Keputusan: docs/DECISION_LOG.md ("RBAC Tahap 0 — keamanan darurat").
